### ISSUE TITLE
Animation gets slower on final output.

### ISSUE THREAD

**Issue by usama-gh** [pankod/canvas2video#16]
We made Reveal By Word text animation. It looks good on Canvas but when we export mp4. There is slight delay between each word. 

We have same Anim Duration on frontend and same on backend. We're using TweenMax on frontend.

We tried both 30 and 60 fps. Both gives same delay between each word.

**Comment by munge** [comment]
our problem is next: we have many text object, that need to animate, we are adding this animation to renderer anim object, but output video has some delay between each animation, any solution? is any default delay between animations? or is any way to start each animation earlier that past object animation will finish?
