### ISSUE TITLE
Does this library support to render video?

### ISSUE THREAD

**Issue by zdying** [pankod/canvas2video#19]
This library is useful, but I want to know if it supports rendering video in the scene. 
I have multiple video clips, and there are transition effects between each video clip. 
How do I achieve this? Can anyone help me? 
thanks！

**Comment by drcivan** [comment]
@zdying Currently canvas2video supports the rendering of a single video clip as the background of generated canvas animation. In future versions, we may consider supporting multiple animation/clips segments and transitions between them. Then, the canvas2video will become more like a "scriptable linear video editing" tool. 

Thank you very much for your feedback.
