### ISSUE TITLE
Project discontinued

### ISSUE THREAD

**Issue by sh9351** [pankod/canvas2video#31]
I think the current project is not maintained; Newly created issues have **0 comments** and **0 actions.**
So I've created a fork/wrapper of this project at [sh9351/withmove](https://github.com/sh9351/withmove) for better maintenance.
When the project is maintained again, I'll commit back to this repository.
Thanks

**Comment by omeraplak** [comment]
Hey @sh9351 👋,
Thank you for contacting us. After remotion.dev came out, we didn't feel the need to develop this project any further. We would be more than happy if you continue by "forking" the project rather than "clone" it 🚀
